CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    CREATE TABLE users (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        google_id character varying(255) NOT NULL,
        google_email character varying(255),
        name character varying(100) NOT NULL,
        picture_url character varying(500),
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_users" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    CREATE TABLE assets (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        name character varying(100) NOT NULL,
        type character varying(20) NOT NULL,
        quantity numeric(18,8) NOT NULL,
        cost_basis numeric(18,2) NOT NULL,
        current_price numeric(18,2) NOT NULL DEFAULT 0.0,
        notes text,
        is_deleted boolean NOT NULL DEFAULT FALSE,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_assets" PRIMARY KEY (id),
        CONSTRAINT "FK_assets_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    CREATE TABLE crypto_details (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        asset_id integer NOT NULL,
        symbol character varying(20) NOT NULL,
        network character varying(50),
        wallet_address character varying(255),
        exchange character varying(100),
        staking boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_crypto_details" PRIMARY KEY (id),
        CONSTRAINT "FK_crypto_details_assets_asset_id" FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    CREATE TABLE real_estate_details (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        asset_id integer NOT NULL,
        property_type character varying(50) NOT NULL,
        square_feet integer,
        bedrooms integer,
        bathrooms numeric(3,1),
        year_built integer,
        address character varying(255) NOT NULL,
        city character varying(100) NOT NULL,
        state character varying(100) NOT NULL,
        zip_code character varying(20),
        country character varying(100) NOT NULL DEFAULT 'US',
        purchase_price numeric(18,2) NOT NULL,
        current_value numeric(18,2) NOT NULL DEFAULT 0.0,
        mortgage_balance numeric(18,2) NOT NULL DEFAULT 0.0,
        monthly_rent numeric(18,2) NOT NULL DEFAULT 0.0,
        monthly_expenses numeric(18,2) NOT NULL DEFAULT 0.0,
        CONSTRAINT "PK_real_estate_details" PRIMARY KEY (id),
        CONSTRAINT "FK_real_estate_details_assets_asset_id" FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    CREATE TABLE stock_details (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        asset_id integer NOT NULL,
        symbol character varying(20) NOT NULL,
        exchange character varying(50),
        sector character varying(100),
        dividend_yield numeric(8,4) NOT NULL DEFAULT 0.0,
        CONSTRAINT "PK_stock_details" PRIMARY KEY (id),
        CONSTRAINT "FK_stock_details_assets_asset_id" FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    CREATE INDEX idx_assets_type ON assets (type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    CREATE INDEX idx_assets_user_id ON assets (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    CREATE INDEX idx_assets_user_type ON assets (user_id, type) WHERE NOT is_deleted;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    CREATE INDEX idx_crypto_symbol ON crypto_details (symbol);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_crypto_details_asset_id" ON crypto_details (asset_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    CREATE INDEX idx_real_estate_city ON real_estate_details (city, state);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_real_estate_details_asset_id" ON real_estate_details (asset_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    CREATE INDEX idx_stock_symbol ON stock_details (symbol);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_stock_details_asset_id" ON stock_details (asset_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_users_google_id" ON users (google_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220174950_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260220174950_InitialCreate', '8.0.11');
    END IF;
END $EF$;
COMMIT;

